export const USER_SELECT_FIELDS = {
  id: true,
  email: true,
  role: true,
  firstName: true,
  lastName: true,
  mobile: true,
  username: true,
  bio: true,
  dob: true,
  gender: true,
  github: true,
  linkedin: true,
  website: true,
  createdAt: true,
  updatedAt: true,
}
